// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAM5mIilCGuaiJW7ZpsGL7ExbU8sGDJ_g',
    appId: '1:534073100100:web:0edd86e1ab63cce179b911',
    messagingSenderId: '534073100100',
    projectId: 'flutter-backend-b3056',
    authDomain: 'flutter-backend-b3056.firebaseapp.com',
    storageBucket: 'flutter-backend-b3056.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIbv0EdoYY9OALCMxh1spCw_T1-JagAFE',
    appId: '1:534073100100:android:900200d867b2a7a479b911',
    messagingSenderId: '534073100100',
    projectId: 'flutter-backend-b3056',
    storageBucket: 'flutter-backend-b3056.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApf3NaSl6pBxlozcfxBvKuSeZfBXDRg44',
    appId: '1:534073100100:ios:36ab99e2b8542abe79b911',
    messagingSenderId: '534073100100',
    projectId: 'flutter-backend-b3056',
    storageBucket: 'flutter-backend-b3056.appspot.com',
    iosClientId: '534073100100-mri757fg8vvu23kqqpttgkq31r54kn5l.apps.googleusercontent.com',
    iosBundleId: 'com.backend.firebaseBackendApp',
  );
}
